version: '3.4'

services:
  magicvila_web:
    hostname: magicvila_web
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "magicvilaonetwo"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/etc/ssl/certs/MagicVila_Web.pfx"
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/etc/ssl/usersecrets/
      - ${USERPROFILE}\.aspnet\https\:/etc/ssl/certs/
  magicvila_vilaapi:
    hostname: magicvila_vilaapi
    ports:
      - "8082:80"
      - "8083:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8083"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "magicvilaonetwo"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/etc/ssl/certs/MagicVila_VilaAPI.pfx"    
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/etc/ssl/usersecrets/
      - ${USERPROFILE}\.aspnet\https\:/etc/ssl/certs/
